spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/start_vue?serverTimezone=Asia/Seoul
    username: startvue
    password: 1234
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
# mybatis ?? ??
mybatis:
  # resources/mapper/ ? ?? ?? xml ??
  config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/**/*.xml
  # alias ??
  # Spring Framework?? ??? ???? ??? ????? ??? ??? ???? ??.
  # IntelluJ? ????? ???? ??? ?? ??? ?.
  # type-aliases-package: com.icia.member.dto
